[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# Redirect all 404s to index.html for SPA-like behavior
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200